Fix Markdown format
Pradumnasaraf/gencli pull request #9
Opened 2024-07-16 19:52 UTC by itsBaivab

## 🛠️ Fixes Issue

## 👨‍💻 Changes proposed

-Used Regex to post process the markdown in Plain text format tried to cover all the markdown scenarios. 

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

If you find and scenario missing, then please leave feedback with re procurable steps.

## 📷 Screenshots

2024-07-17 15:37 UTC, Pradumnasaraf reviewed
Hey,

Thanks for the PR. I was thinking that instead of using regexp, we could mention in the prompt that we want the output ~~with~~ without horizontal rules, italics, etc. What do you think?

2024-07-22 10:22 UTC, Pradumnasaraf commented
> In my opinion for all kind of question hard coding a single answer format is not going to look good. Additionally, before using regex I was tiring to do some prompt manipulation to get our desired answer format, but the results are not consistent throughout each and every question.
> 
> also tried multiple markdown rendering modules but is tremendously affecting the response speed by 5..6 sec.

I agree, that can be painful! Thank you for your thoughts :)

2024-07-22 10:36 UTC, Pradumnasaraf requested changes
Hey,

Thanks for the PR. Inclusing some edge cases

2024-07-22 10:36 UTC, Pradumnasaraf commented on cmd/searchCmd.go
> +	input = re.ReplaceAllString(input, "$1")
```suggestion
	// Remove italic formatting
	re = regexp.MustCompile(`_([^_]+)_|\*([^*]+)\*`)
	input = re.ReplaceAllString(input, "$1$2")

	// Remove bold formatting
	re = regexp.MustCompile(`\*\*([^*]+)\*\*|__([^_]+)__`)
	input = re.ReplaceAllString(input, "$1$2")
```

2024-07-22 10:46 UTC, Pradumnasaraf commented
Seems like it's working correctly as well:

![Screenshot 2024-07-22 at 4 14 56 PM](https://github.com/user-attachments/assets/9e73aee4-bada-4a89-905a-26e41e0ec456)

2024-07-22 10:48 UTC, itsBaivab commented
> Seems like it's working correctly as well:
> 
> ![Screenshot 2024-07-22 at 4 14 56 PM](https://private-user-images.githubusercontent.com/51878265/350936717-9e73aee4-bada-4a89-905a-26e41e0ec456.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDU0OTAsIm5iZiI6MTcyMTY0NTE5MCwicGF0aCI6Ii81MTg3ODI2NS8zNTA5MzY3MTctOWU3M2FlZTQtYmFkYS00YTg5LTkwNWEtMjZlNDFlMGVjNDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDEwNDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1Mjc1ODJiZmQ5MWRjZWViYzYxZWJlMzk4YWNjNjc2ZTZiNTNlMDQ4MzRhM2Q5MjgxYzZhZWVhYTI2NmY5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nSIAJ8yKyBougLgAoT6zE7irWssKUHh1KNF8znzbO5w)

is it still generating bold formating?

2024-07-22 10:56 UTC, itsBaivab commented
> > Seems like it's working correctly as well:
> > ![Screenshot 2024-07-22 at 4 14 56 PM](https://private-user-images.githubusercontent.com/51878265/350936717-9e73aee4-bada-4a89-905a-26e41e0ec456.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDU0OTAsIm5iZiI6MTcyMTY0NTE5MCwicGF0aCI6Ii81MTg3ODI2NS8zNTA5MzY3MTctOWU3M2FlZTQtYmFkYS00YTg5LTkwNWEtMjZlNDFlMGVjNDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDEwNDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1Mjc1ODJiZmQ5MWRjZWViYzYxZWJlMzk4YWNjNjc2ZTZiNTNlMDQ4MzRhM2Q5MjgxYzZhZWVhYTI2NmY5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nSIAJ8yKyBougLgAoT6zE7irWssKUHh1KNF8znzbO5w)
> 
> is it still generating bold formatting?

![image](https://github.com/user-attachments/assets/efa43dce-5ffc-4fe6-8cdf-8ae86af0704c)


This is the response I am getting

2024-07-24 18:02 UTC, Pradumnasaraf approved these changes
Let's merge it. Improvements can come later in the other PRs.

Thank you so much!

2024-07-24 18:02 UTC, merged